In [9]:
import numpy as np
from objparser import ObjParser
from objmodel import ObjModel
from scene import Scene

In [10]:
filename = 'bunny_model.obj'
texture_filename = 'bunny.jpg'

bunnyModel = ObjParser.processObj(filename)
bunnyTexture = ObjParser.processTexture(texture_filename)
bunnyModel.addTexture(bunnyTexture)

In [11]:
filename = 'frog_model.obj'
texture_filename = 'frog.jpg'

frogModel = ObjParser.processObj(filename)
frogTexture = ObjParser.processTexture(texture_filename)
frogModel.addTexture(frogTexture)

In [12]:
light = np.array([0, 1, 1])
camera = np.array([0, 0, 1])
height = 1080
width = 1920
degrees = {'x' : 0, 'y' : 130, 'z' : 0}

In [13]:
scene = Scene(height, width, light, camera)
scene.setShading('phong')

In [14]:
init_scale = 500
model_shift = np.array([0, -37, 0])
rotateAxis = np.array([0,1,0], dtype='float64')
rotateDegree = 120

index = 0;
scene.addModel(init_scale, bunnyModel)
scene.rotateModelQuaternion(rotateDegree, rotateAxis, index)
scene.scaleModel(init_scale, index)
scene.shiftModel(model_shift, index)
scene.perspectiveTransformModel(0.15, init_scale, index)
print(scene.objModels[index].v)

[[1.01389390e+03 4.90466624e+02 2.37849729e-01]
 [1.01145951e+03 4.88873838e+02 2.37774545e-01]
 [1.01316393e+03 4.88666265e+02 2.37124768e-01]
 ...
 [1.01913593e+03 3.75735375e+02 2.21152302e-01]
 [1.02075475e+03 3.76926124e+02 2.20997998e-01]
 [1.02683091e+03 3.76015488e+02 2.19084715e-01]]


In [15]:
init_scale = 250
model_shift = np.array([200, -80, 0])
rotateAxis1 = np.array([1,0,0], dtype='float64')
rotateAxis = np.array([0,1,0], dtype='float64')
rotateDegree = 150
rotateDegree1 = -90

index = 1
scene.addModel(init_scale, frogModel)
scene.rotateModelQuaternion(rotateDegree1, rotateAxis1, index)
scene.rotateModelQuaternion(rotateDegree, rotateAxis, index)
scene.scaleModel(init_scale , index)
scene.shiftModel(model_shift, index)
scene.perspectiveTransformModel(10.75, init_scale, index)
print(scene.objModels[index].v)

[[987.49412211 548.0598999   13.15462987]
 [987.88756164 548.72218468  13.12457879]
 [986.54051846 548.75266751  13.07886994]
 ...
 [984.61387783 537.9833361   15.24795483]
 [984.77684589 538.01771299  15.20970471]
 [984.9685801  538.06204815  15.17065555]]


In [16]:
scene.renderScene("test_full_pipeline.png")